version: "3"

services:
  # db:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - ./db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: sonar
  #     POSTGRES_USER: sonar
  # sonarqube:
  #   image: sonarqube
  #   restart: always
  #   ports:
  #     - 9000:9000
  #     - 9092:9092
  #   depends_on:
  #      - db
  #   environment:
  #     SONARQUBE_JDBC_USERNAME: sonar
  #     SONARQUBE_JDBC_PASSWORD: sonar
  #     SONARQUBE_JDBC_URL: jdbc:postgresql://db/sonar
      

  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./code:/code
      - ./default.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: php7.3-fpm
    volumes:
      - ./code:/code